# INX Future Inc. Employee Performance Analysis

This project analyzes employee data to understand performance patterns, identify important performance factors, and support data-driven recommendations.

### Objectives
- Load the original employee performance dataset.
- Understand the dataset's structure.
- Check data types and missing values.
- Identify duplicate records.
- Clean the data based on the findings.
- Save the cleaned dataset for further analysis.


## 1. Data Processing

This notebook covers dataset loading, data quality assessment, data cleaning, and preparation of the processed dataset for further analysis.

## 2. Import Libraries

Import the required libraries for data manipulation and dataset inspection.

In [1]:
import pandas as pd 
import numpy as np 
from pathlib import Path

## 3. Load Dataset

Load the original employee dataset from the project's raw data directory. The original dataset will remain unchanged so that all cleaning steps can be traced back to the source.

In [2]:
Data_Path = Path("../../data/raw/INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xls")

df_raw = pd.read_excel(Data_Path)
df = df_raw.copy() 

print(f"Dataset loaded successfully: {df.shape[0]} rows and {df.shape[1]} columns")

Dataset loaded successfully: 1200 rows and 28 columns

## 4. Dataset Preview

Display the first five records to inspect the dataset and understand how employee information is organized.

In [3]:
df.head()

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,...,4,10,2,2,10,7,0,8,No,3
1,E1001006,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,...,4,20,2,3,7,7,1,7,No,3
2,E1001007,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,...,3,20,2,3,18,13,1,12,No,4
3,E1001009,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,...,2,23,2,2,21,6,12,6,No,3
4,E1001010,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,...,4,10,1,3,2,2,2,2,No,3

### Finding
The dataset contains employee demographic, job-related, experience, and performance information. The target variable for this project is `PerformanceRating`.

## 5. Dataset Information

Let's check the dataset's columns, data types, and missing values before starting the data cleaning process.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EmpNumber                     1200 non-null   object
 1   Age                           1200 non-null   int64
 2   Gender                        1200 non-null   object
 3   EducationBackground           1200 non-null   object
 4   MaritalStatus                 1200 non-null   object
 5   EmpDepartment                 1200 non-null   object
 6   EmpJobRole                    1200 non-null   object
 7   BusinessTravelFrequency       1200 non-null   object
 8   DistanceFromHome              1200 non-null   int64
 9   EmpEducationLevel             1200 non-null   int64
 10  EmpEnvironmentSatisfaction    1200 non-null   int64
 11  EmpHourlyRate                 1200 non-null   int64
 12  EmpJobInvolvement             1200 non-null   int64
 13  EmpJobLevel                   1200 non-null   int64
 14  EmpJobSatisfaction            1200 non-null   int64
 15  NumCompaniesWorked            1200 non-null   int64
 16  OverTime                      1200 non-null   object
 17  EmpLastSalaryHikePercent      1200 non-null   int64
 18  EmpRelationshipSatisfaction   1200 non-null   int64
 19  TotalWorkExperienceInYears    1200 non-null   int64
 20  TrainingTimesLastYear         1200 non-null   int64
 21  EmpWorkLifeBalance            1200 non-null   int64
 22  ExperienceYearsAtThisCompany  1200 non-null   int64
 23  ExperienceYearsInCurrentRole  1200 non-null   int64
 24  YearsSinceLastPromotion       1200 non-null   int64
 25  YearsWithCurrManager          1200 non-null   int64
 26  Attrition                     1200 non-null   object
 27  PerformanceRating             1200 non-null   int64
dtypes: int64(19), object(9)
memory usage: 262.6+ KB

### Finding
The dataset contains 1,200 records and 28 columns. There are no missing values according to the non-null counts, and the columns have integer and object data types.

## 6. Duplicate Records

Check for duplicate rows to determine whether any records need further investigation before cleaning the dataset.

In [5]:
df.duplicated().sum()

np.int64(0)

### Finding
No duplicate rows were found in the dataset. No duplicate-row removal is required at this stage.

## 7. Missing Values

Check each column for missing values before proceeding with data cleaning.

In [6]:
df.isnull().sum()

EmpNumber                       0
Age                             0
Gender                          0
EducationBackground             0
MaritalStatus                   0
EmpDepartment                   0
EmpJobRole                      0
BusinessTravelFrequency         0
DistanceFromHome                0
EmpEducationLevel               0
EmpEnvironmentSatisfaction      0
EmpHourlyRate                   0
EmpJobInvolvement               0
EmpJobLevel                     0
EmpJobSatisfaction              0
NumCompaniesWorked              0
OverTime                        0
EmpLastSalaryHikePercent        0
EmpRelationshipSatisfaction     0
TotalWorkExperienceInYears      0
TrainingTimesLastYear           0
EmpWorkLifeBalance              0
ExperienceYearsAtThisCompany    0
ExperienceYearsInCurrentRole    0
YearsSinceLastPromotion         0
YearsWithCurrManager            0
Attrition                       0
PerformanceRating               0
dtype: int64

### Finding
No missing values were found in any column. Missing-value treatment is not required.

## 8. Performance Rating Distribution

Check the number of employees in each performance rating category to understand how ratings are distributed.

In [7]:
df["PerformanceRating"].value_counts().sort_index()

PerformanceRating
2    194
3    874
4    132
Name: count, dtype: int64

### Finding
Most employees have a performance rating of 3 (874 employees), followed by rating 2 (194 employees) and rating 4 (132 employees). Rating 3 is the most common category in the dataset.

## 9. Check Unique Values

Check the number of unique values in each column to understand the data and identify any unexpected categories.

In [8]:
df.nunique()

EmpNumber                       1200
Age                               43
Gender                             2
EducationBackground                6
MaritalStatus                      3
EmpDepartment                      6
EmpJobRole                        19
BusinessTravelFrequency            3
DistanceFromHome                  29
EmpEducationLevel                  5
EmpEnvironmentSatisfaction         4
EmpHourlyRate                     71
EmpJobInvolvement                  4
EmpJobLevel                        5
EmpJobSatisfaction                 4
NumCompaniesWorked                10
OverTime                           2
EmpLastSalaryHikePercent          15
EmpRelationshipSatisfaction        4
TotalWorkExperienceInYears        40
TrainingTimesLastYear              7
EmpWorkLifeBalance                 4
ExperienceYearsAtThisCompany      37
ExperienceYearsInCurrentRole      19
YearsSinceLastPromotion           16
YearsWithCurrManager              18
Attrition                          2
PerformanceRating                  3
dtype: int64

### Finding
The dataset contains both numerical and categorical variables. `EmpNumber` has 1,200 unique values, indicating that each employee has a distinct identifier. `PerformanceRating` has three unique values: 2, 3, and 4.

## 10. Statistical Summary

Review summary statistics for numerical columns to understand their ranges, central values, and variation before proceeding with further analysis.

In [9]:
df.describe()

,Age,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,PerformanceRating
count,1200.000000,1200.000000,1200.00000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,36.918333,9.165833,2.89250,2.715833,65.981667,2.731667,2.067500,2.732500,2.665000,15.222500,2.725000,11.330000,2.785833,2.744167,7.077500,4.291667,2.194167,4.105000,2.948333
std,9.087289,8.176636,1.04412,1.090599,20.211302,0.707164,1.107836,1.100888,2.469384,3.625918,1.075642,7.797228,1.263446,0.699374,6.236899,3.613744,3.221560,3.541576,0.518866
min,18.000000,1.000000,1.00000,1.000000,30.000000,1.000000,1.000000,1.000000,0.000000,11.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,30.000000,2.000000,2.00000,2.000000,48.000000,2.000000,1.000000,2.000000,1.000000,12.000000,2.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000,3.000000
50%,36.000000,7.000000,3.00000,3.000000,66.000000,3.000000,2.000000,3.000000,2.000000,14.000000,3.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000,3.000000
75%,43.000000,14.000000,4.00000,4.000000,83.000000,3.000000,3.000000,4.000000,4.000000,18.000000,4.000000,15.000000,3.000000,3.000000,10.000000,7.000000,3.000000,7.000000,3.000000
max,60.000000,29.000000,5.00000,4.000000,100.000000,4.000000,5.000000,4.000000,9.000000,25.000000,4.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000,4.000000

### Finding
The dataset contains 1,200 records, with no missing values in the numerical columns. Employee ages range from 18 to 60 years, while total work experience ranges from 0 to 40 years. Some experience-related and training columns have minimum values of 0, which will be reviewed during data validation.

## 11. Categorical Value Review

Inspect the unique values in categorical columns to check for inconsistent labels or unexpected categories before further processing.

In [10]:
categorical_cols = df.select_dtypes(include="object").columns.drop("EmpNumber")

for col in categorical_cols:
    print(f"\n{col}:")
    print(df[col].value_counts())

Gender:
Gender
Male      725
Female    475
Name: count, dtype: int64

EducationBackground:
EducationBackground
Life Sciences       492
Medical             384
Marketing           137
Technical Degree    100
Other                66
Human Resources      21
Name: count, dtype: int64

MaritalStatus:
MaritalStatus
Married     548
Single      384
Divorced    268
Name: count, dtype: int64

EmpDepartment:
EmpDepartment
Sales                     373
Development               361
Research & Development    343
Human Resources            54
Finance                    49
Data Science               20
Name: count, dtype: int64

EmpJobRole:
EmpJobRole
Sales Executive              270
Developer                    236
Manager R&D                   94
Research Scientist            77
Sales Representative          69
Laboratory Technician         64
Senior Developer              52
Manager                       51
Finance Manager               49
Human Resources               45
Technical Lead                38
Manufacturing Director        33
Healthcare Representative     33
Data Scientist                20
Research Director             19
Business Analyst              16
Senior Manager R&D            15
Delivery Manager              12
Technical Architect            7
Name: count, dtype: int64

BusinessTravelFrequency:
BusinessTravelFrequency
Travel_Rarely        846
Travel_Frequently    222
Non-Travel           132
Name: count, dtype: int64

OverTime:
OverTime
No     847
Yes    353
Name: count, dtype: int64

Attrition:
Attrition
No     1022
Yes     178
Name: count, dtype: int64

### Finding
The categorical columns contain employee demographics, education, department, job role, travel frequency, overtime, and attrition information. No obvious inconsistent labels are visible in the displayed categories. `EmpNumber` is a unique employee identifier and should not be used as a predictive feature.

## 12. Numerical Data Validation

Review the ranges of numerical columns to identify values that may need further investigation before analysis and model development.

In [11]:
df.describe().T[["min", "max"]]

                               min    max
Age                           18.0   60.0
DistanceFromHome               1.0   29.0
EmpEducationLevel              1.0    5.0
EmpEnvironmentSatisfaction     1.0    4.0
EmpHourlyRate                 30.0  100.0
EmpJobInvolvement              1.0    4.0
EmpJobLevel                    1.0    5.0
EmpJobSatisfaction             1.0    4.0
NumCompaniesWorked             0.0    9.0
EmpLastSalaryHikePercent      11.0   25.0
EmpRelationshipSatisfaction    1.0    4.0
TotalWorkExperienceInYears     0.0   40.0
TrainingTimesLastYear          0.0    6.0
EmpWorkLifeBalance             1.0    4.0
ExperienceYearsAtThisCompany   0.0   40.0
ExperienceYearsInCurrentRole   0.0   18.0
YearsSinceLastPromotion        0.0   15.0
YearsWithCurrManager           0.0   17.0
PerformanceRating              2.0    4.0

### Finding
The numerical columns have ranges that are generally plausible for employee data. Some experience-related columns and `TrainingTimesLastYear` contain zero values, which may be valid. Further checks are needed before deciding whether any values require correction.

## 13. Outlier Detection

Check for unusually high or low values in selected numerical columns. This will help determine whether any observations need further investigation before analysis and model development.

In [12]:
check_cols = [
    "Age",
    "DistanceFromHome",
    "TotalWorkExperienceInYears",
    "ExperienceYearsAtThisCompany",
    "EmpLastSalaryHikePercent"
]

for col in check_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outlier_count = ((df[col] < lower_bound) | (df[col] > upper_bound)).sum()

    print(f"{col}: {outlier_count} potential outliers")

Age: 0 potential outliers
DistanceFromHome: 0 potential outliers
TotalWorkExperienceInYears: 51 potential outliers
ExperienceYearsAtThisCompany: 56 potential outliers
EmpLastSalaryHikePercent: 0 potential outliers

### Finding
The IQR method identified 51 potential outliers in `TotalWorkExperienceInYears` and 56 in `ExperienceYearsAtThisCompany`. No potential outliers were detected in the other three columns. These values are retained because they represent long-serving employees, are consistent with employee age (the logical checks found no impossible values), and are not data errors. Removing them would also discard real employees from a dataset of only 1,200 records.

## 14. Data Cleaning Decision

After checking the data, I found nothing that needed fixing. There were no missing values, no duplicate employees, no inconsistent labels, and no impossible values. The few unusually high experience values belong to long-serving employees, so I kept them. Because of this, the dataset is saved as it is, and the original raw file in `data/raw` stays untouched.

## 15. Feature Engineering

In this step, a new feature named `ExperienceBeforeCurrentCompany` is created by subtracting the employee's experience at the current company from their total work experience.

In [13]:
df["ExperienceBeforeCurrentCompany"] = (
    df["TotalWorkExperienceInYears"]
    - df["ExperienceYearsAtThisCompany"]
)

In [14]:
df[
    [
        "TotalWorkExperienceInYears",
        "ExperienceYearsAtThisCompany",
        "ExperienceBeforeCurrentCompany"
    ]
].head()

,TotalWorkExperienceInYears,ExperienceYearsAtThisCompany,ExperienceBeforeCurrentCompany
0,10,10,0
1,20,7,13
2,20,18,2
3,23,21,2
4,10,2,8

In [15]:
negative_values = (df["ExperienceBeforeCurrentCompany"] < 0).sum()
missing_values = df["ExperienceBeforeCurrentCompany"].isna().sum()

print("Negative values:", negative_values)
print("Missing values:", missing_values)

Negative values: 0
Missing values: 0

## 16. Save the Processed Dataset

Save the validated dataset in the processed data directory for use in exploratory data analysis and model development.

In [16]:
Processed_Path = Path("../../data/processed/employee_performance_processed.csv")

df.to_csv(Processed_Path, index=False)